K8SPSMDB-268: certmanager quorum error
percona/percona-server-mongodb-operator pull request #434
Opened 2020-10-05 11:51 UTC by qJkee

When using certmanager, we can not create cluster successfully because of certificates errors

2020-10-07 06:20 UTC, toabi commented
Nice. Noticed the missing apiGroup recently too. Would be even more awesome if it would work with 1.0+ :D

2020-10-08 14:08 UTC, qJkee commented
> Nice. Noticed the missing apiGroup recently too. Would be even more awesome if it would work with 1.0+ :D

Hey Tobias!
I'm fixing the final issue with tls, since somehow mongodb rejects certificates provided by certmanager
Doing all my best =)

2020-10-09 18:13 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-aac3804a

2020-10-09 18:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

2020-10-12 16:18 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-c55095e5

2020-10-12 16:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

2020-10-12 16:31 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-07c333f1

2020-10-12 16:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade | passed |
| monitoring | passed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

2020-10-13 08:00 UTC, delgod requested changes

2020-10-13 08:00 UTC, delgod commented on pkg/psmdb/mongo/mongo.go
> -
I believe if allowUnsafeConfiguration=false we should fetch CA from secret and use TLS connection between Operator and MongoDB

2020-10-13 13:17 UTC, delgod requested changes

2020-10-13 13:17 UTC, delgod commented on pkg/controller/perconaservermongodb/version.go
> +	}
why not move this inside `Dial` function?

2020-10-13 13:17 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-de187194

2020-10-16 08:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | failed |
| upgrade | failed |
| one-pod | failed |
| upgrade-consistency | failed |
| limits | failed |
| monitoring | failed |
| self-healing | failed |
| demand-backup | failed |
| scaling | failed |
| operator-self-healing | failed |
| monitoring-2-0 | failed |
| scheduled-backup | failed |
| security-context | failed |
| arbiter | failed |
| service-per-pod | failed |
| liveness | failed |
| users | failed |

2020-10-16 10:46 UTC, hors requested changes
@qJkee  please add simple DB connection check into init-deploy test. We need to get the number of DB connections and the value should not be more than 5.

2020-10-16 11:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| users | failed |

2020-10-16 11:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| operator-self-healing | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| users | failed |

2020-10-16 15:50 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-fc78df9a

2020-10-16 15:50 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

2020-10-19 11:10 UTC, delgod approved these changes

2020-10-19 12:03 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-434-eeb4d809

2020-10-19 12:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

2020-10-19 17:41 UTC, hors approved these changes

2020-10-20 08:27 UTC, blez approved these changes

2020-10-20 08:32 UTC, merged