K8SPSMDB-282 integrate pmm into PSMDBO
percona/percona-server-mongodb-operator pull request #443
Opened 2020-10-25 15:55 UTC by hors

2020-10-25 17:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| scaling | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-10-27 10:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| monitoring | failed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-08 02:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | failed |
| scaling | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| security-context | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |
| users | failed |

2020-11-11 00:43 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-11 09:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-11 17:09 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| init-deploy | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-11 17:38 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| limits | passed |
| monitoring | failed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-11 19:38 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-13 15:10 UTC, delgod approved these changes

2020-11-16 11:46 UTC, delgod requested changes

2020-11-16 11:46 UTC, delgod commented on pkg/psmdb/pmm.go
> +			Value: "sleep 10; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate reboot",
```suggestion
			Value: "sleep 10; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate restart",
```

2020-11-16 20:21 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | failed |
| upgrade | failed |
| limits | passed |
| scaling | passed |
| self-healing | passed |
| security-context | failed |
| monitoring | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| arbiter | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |

2020-11-18 14:27 UTC, hors commented on pkg/psmdb/pmm.go
> +			Value: "sleep 10; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate reboot",
fixed

2020-11-19 07:24 UTC, delgod requested changes

2020-11-19 07:24 UTC, delgod commented on pkg/psmdb/pmm.go
> +			Value: "sleep 10; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate restart",
please use `pmm-admin status --wait` 
```suggestion
			Value: "pmm-admin status --wait; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate restart",
```

2020-11-23 11:44 UTC, hors commented on pkg/psmdb/pmm.go
> +			Value: "sleep 10; pmm-admin add $(DB_TYPE)" + pmmServerArgs + "; pmm-admin annotate restart",
yes, I know it. I have updated this PR

2020-11-23 11:46 UTC, delgod approved these changes

2020-11-23 14:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | failed |
| upgrade | failed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| operator-self-healing | passed |
| security-context | failed |
| monitoring | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| arbiter | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |

2020-12-01 18:34 UTC, delgod requested changes
it is needed to add param options for mongod and mongos

2020-12-03 17:40 UTC, hors commented
> it is needed to add param options for mongod and mongos

yes, we need but firstly we need to add pmm client to mongos via a separate PR. And I have a separate task regarding param options. I will appreciate very much if you all stop adding additional requirements to this PR :) Let's  try to merge it.

2020-12-03 20:51 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| storage | passed |
| init-deploy | passed |
| upgrade | failed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| security-context | failed |
| monitoring | failed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| scheduled-backup | failed |

2020-12-03 20:54 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |

2020-12-04 12:14 UTC, delgod requested changes

2020-12-04 12:14 UTC, delgod commented on pkg/psmdb/pmm.go
> +func PMMContainer(spec api.PMMSpec, secrets string, customLogin bool, clusterName string, v120OrGreater bool, v170OrGreater bool) corev1.Container {
```suggestion
func PMMContainer(spec api.PMMSpec, secrets string, customLogin bool, clusterName string, v120OrGreater bool, v160OrGreater bool) corev1.Container {
```

2020-12-04 12:14 UTC, hors commented on pkg/psmdb/pmm.go
> +func PMMContainer(spec api.PMMSpec, secrets string, customLogin bool, clusterName string, v120OrGreater bool, v170OrGreater bool) corev1.Container {
thank you!

2020-12-04 12:57 UTC, delgod approved these changes

2020-12-04 13:29 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | failed |
| upgrade | failed |
| limits | passed |
| scaling | passed |
| self-healing | passed |
| security-context | failed |
| monitoring | failed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| scheduled-backup | failed |

2020-12-04 15:28 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| monitoring | failed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |

2020-12-04 16:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade | passed |
| monitoring | failed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |

2020-12-04 19:05 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-443-0b7ba606

2020-12-04 19:05 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| arbiter | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-07 06:54 UTC, delgod requested changes

2020-12-07 12:20 UTC, hors commented on Jenkinsfile
> -                        runTest('monitoring', 'basic')
It is test for PMM1. We need to support official PMM2 only. Why should we support unofficial pmm docker image? P.S. I have discussed it with @spron-in  and he confirmed that we need to support only official PMM2.

2020-12-07 12:23 UTC, delgod commented on Jenkinsfile
> -                        runTest('monitoring', 'basic')
can we remove it at all in such case?

2020-12-07 12:44 UTC, hors commented on Jenkinsfile
> -                        runTest('monitoring', 'basic')
yes, I will clean up the old code  in separate PR.

2020-12-07 12:48 UTC, delgod approved these changes

2020-12-07 13:30 UTC, qJkee approved these changes

2020-12-07 14:14 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-443-7c14cd53

2020-12-07 14:14 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-07 14:15 UTC, merged