K8SPSMDB-286 create FAQ - initial version
percona/percona-server-mongodb-operator pull request #451
Opened 2020-11-10 08:12 UTC by fiowro

2020-11-16 11:47 UTC, delgod approved these changes

2020-11-18 08:06 UTC, spron-in requested changes

2020-11-18 08:06 UTC, spron-in commented on source/faq.rst
> +setup.
please align this section with PXC faq

2020-12-03 07:38 UTC, spron-in approved these changes
lgtm

2020-12-03 07:47 UTC, merged