K8SPSMDB-266 Doc update for secret update
percona/percona-server-mongodb-operator pull request #470
Opened 2020-11-26 14:43 UTC by cap1984

Since we've switched to stringData secret format, related docs
should be updated.

2020-11-26 14:49 UTC, delgod requested changes

2020-11-26 14:49 UTC, delgod commented on source/users.rst
>  values.
@fiowro can you take a look how we can improve wording here?

2020-11-27 08:08 UTC, delgod approved these changes

2020-11-27 11:19 UTC, fiowro approved these changes
lgtm)

2020-12-03 07:42 UTC, spron-in approved these changes
lgtm, needs release

2020-12-03 09:47 UTC, merged