K8SPSMDB-277 Add Licenses from packages
percona/percona-server-mongodb-operator pull request #474
Opened 2020-11-27 16:44 UTC by cap1984

GCP requests a complete set of license files from libs used by
the operator for the marketplace certification.

2020-11-27 18:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| init-deploy | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| users | passed |

2020-11-30 08:47 UTC, delgod requested changes

2020-11-30 08:47 UTC, delgod commented on build/Dockerfile
> +
another idea, only explicit depencies
```
awk '{print$1}' go.mod \
    | egrep -v -e '^(replace|require|go|module|\))$' \
    | grep -v "^$" \
    | xargs -I{} sh -c "test -d vendor/{} && ls vendor/{}/LICENSE"
```
decision up to @spron-in

2020-11-30 12:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | failed |
| upgrade | failed |
| upgrade-consistency | passed |
| monitoring | failed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-11-30 13:52 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-474-fe04f6c6

2020-11-30 13:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| self-healing | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-03 07:39 UTC, spron-in submitted a review, later dismissed
lgtm

2020-12-03 12:01 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-03 17:16 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-474-92552afa

2020-12-03 17:16 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-03 18:31 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-474-284e96a2

2020-12-03 18:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| init-deploy | passed |
| monitoring | passed |
| self-healing | passed |
| upgrade-consistency | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| operator-self-healing | passed |
| arbiter | passed |
| security-context | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2020-12-03 22:09 UTC, hors submitted a review, later dismissed

2020-12-04 11:04 UTC, merged