K8SPSMDB-282 document PMM support
percona/percona-server-mongodb-operator pull request #501
Opened 2020-12-10 23:40 UTC by fiowro

2020-12-15 11:37 UTC, PaulJacobs-percona reviewed
Various minor grammatical suggestions

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +That's why PMM Server and PMM Client are to be installed separately.
/are to be/need to be/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +The Percona Monitoring and Management (PMM) `provides an excellent
/^The //

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +to monitor Percona Server for MongoDB.
/to monitor/of monitoring/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +Installing the PMM Server
/the//

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +Installing the PMM Client
/the//

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +      ``monitoring-service`` by default) is the same as value specified
/as value/as the value/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +   -  check that ``PMM_SERVER_USER`` key in the
/that/that the/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +      secrets file contains password specified for the PMM Server during its
/contains password/contains the password/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +      installation
Add a full stop

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +         The file contains all values for each key/value pair in convenient
/in/in a/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +#. Check that correspondent Pods are
/correspondent/corresponding/

2020-12-15 11:37 UTC, PaulJacobs-percona commented on source/monitoring.rst
> +convenient from the user's point of view. But the resulting Secrets
/convenient/which is convenient/

2020-12-16 08:18 UTC, delgod requested changes

2020-12-16 08:18 UTC, delgod commented on source/monitoring.rst
> +      additional ``-service`` suffix.
it was actual if PMM installed inside kubernetes, now it is just "hostname" of  PMM Server

2020-12-16 10:21 UTC, tplavcic approved these changes

2020-12-17 08:39 UTC, merged