K8SPSMDB-370 Change messages for meta waitining
percona/percona-server-mongodb-operator pull request #536
Opened 2021-01-29 12:56 UTC by nonemax

There are some confusing messages in the operator log when backing up and restoring the cluster, but both operations are successful. The reason why there is this messages it because PBM need some time for syncing and start work. So we dont have any meta information about backup or restore before PBM starts

2021-01-29 15:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | failed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| scheduled-backup | failed |
| version-service | passed |
| users | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |

2021-02-01 07:01 UTC, dAdAbird submitted a review, later dismissed

2021-02-01 10:31 UTC, spron-in requested changes

2021-02-01 10:31 UTC, spron-in commented on pkg/controller/perconaservermongodbbackup/backup.go
> +		log.Info("Waiting for backup meta", "PBM name", cr.Status.PBMname, "backup", cr.Name)
```suggestion
		log.Info("Waiting for backup metadata", "PBM name", cr.Status.PBMname, "backup", cr.Name)
```

2021-02-01 10:31 UTC, spron-in commented on pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
> +		log.Info("Waiting for restore meta", "PBM name", cr.Status.PBMname, "restore", cr.Name, "backup", cr.Spec.BackupName)
```suggestion
		log.Info("Waiting for restore metadata", "PBM name", cr.Status.PBMname, "restore", cr.Name, "backup", cr.Spec.BackupName)
```

2021-02-01 10:55 UTC, nonemax commented on pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
> +		log.Info("Waiting for restore meta", "PBM name", cr.Status.PBMname, "restore", cr.Name, "backup", cr.Spec.BackupName)
done https://github.com/percona/percona-server-mongodb-operator/pull/536/commits/3bf8a664776bed687b6d30dff9e6be5f6b227a69

2021-02-01 10:56 UTC, nonemax commented on pkg/controller/perconaservermongodbbackup/backup.go
> +		log.Info("Waiting for backup meta", "PBM name", cr.Status.PBMname, "backup", cr.Name)
done https://github.com/percona/percona-server-mongodb-operator/pull/536/commits/3bf8a664776bed687b6d30dff9e6be5f6b227a69

2021-02-01 11:30 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-536-58a95e62

2021-02-01 11:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

2021-02-01 12:49 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-536-3bf8a664

2021-02-01 12:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| one-pod | passed |
| demand-backup | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | passed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | passed |

2021-02-02 12:58 UTC, delgod approved these changes

2021-02-02 13:04 UTC, spron-in approved these changes
lgtm

2021-02-02 13:19 UTC, dAdAbird approved these changes

2021-02-02 13:22 UTC, merged

2021-02-02 15:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | failed |
| operator-self-healing | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | passed |