Backup retention based on 'Keep' parameter
percona/percona-server-mongodb-operator pull request #539
Opened 2021-02-02 18:43 UTC by blez

2021-02-02 19:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2021-02-02 21:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| security-context | failed |
| arbiter | passed |
| operator-self-healing | passed |
| scheduled-backup | failed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| upgrade | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

2021-02-02 21:57 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | failed |
| security-context | failed |
| service-per-pod | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |

2021-02-02 22:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | failed |
| arbiter | passed |
| service-per-pod | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |

2021-02-03 07:16 UTC, delgod requested changes

2021-02-03 09:38 UTC, blez commented on pkg/apis/psmdb/v1/psmdb_types.go
> +	Name            string              `json:"name,omitempty"`
https://github.com/percona/percona-server-mongodb-operator/pull/539/commits/466be4cb00ef0f20c99ef239d34525fa09b308e2

2021-02-03 09:56 UTC, qJkee commented on pkg/controller/perconaservermongodb/backup.go
> +	if h.Len() <= keep {
we don't need this check, because we already checked at 101 line

2021-02-03 09:58 UTC, qJkee approved these changes

2021-02-03 12:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | failed |
| security-context | failed |
| operator-self-healing | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| upgrade | failed |
| version-service | passed |
| users | passed |

2021-02-03 12:50 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| operator-self-healing | passed |
| service-per-pod | passed |
| scheduled-backup | failed |
| rs-shard-migration | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | failed |

2021-02-03 13:28 UTC, delgod approved these changes

2021-02-03 13:28 UTC, merged

2021-02-03 20:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | failed |
| scheduled-backup | failed |
| liveness | passed |
| smart-update | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| upgrade-sharded | failed |