K8SPSMDB-403 fix: some typos in comments/messages
percona/percona-server-mongodb-operator pull request #570
Opened 2021-02-22 12:23 UTC by ollevche

https://jira.percona.com/browse/K8SPSMDB-403

2021-02-22 12:29 UTC, delgod approved these changes

2021-02-22 15:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| users | passed |
| upgrade | failed |
| rs-shard-migration | passed |
| data-sharded | passed |

2021-02-22 16:34 UTC, hors commented on pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
> +// reconcile backup. first we check if there are concurrent job running
```suggestion
// reconcile backup. firstly we check if there are concurrent jobs running
```

2021-02-22 16:35 UTC, hors commented on pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
> +		// may be it's k8s v1.10 and earlier (e.g. oc3.9) that doesn't support status updates
```suggestion
		// maybe it's k8s v1.10 and earlier (e.g. oc3.9) that doesn't support status updates
```

2021-02-22 16:42 UTC, hors requested changes
please see comments

2021-02-23 10:58 UTC, JNKPercona commented
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-570-d85aa188

2021-02-23 10:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| data-sharded | passed |

2021-02-23 12:27 UTC, delgod approved these changes

2021-02-23 12:29 UTC, merged