K8SPSMDB-405 mention strict preserving major versions option in updat…
percona/percona-server-mongodb-operator pull request #574
Opened 2021-02-23 08:54 UTC by fiowro

…e doc

2021-02-24 07:55 UTC, delgod commented
maybe it is also needed to mention this behavior in all installation docs.
up to @spron-in

2021-02-24 15:29 UTC, cap1984 submitted a review, later dismissed

2021-02-24 15:33 UTC, fiowro commented
I have checked the installation docs (kubernetes.rst and openshift.rst). We do not describe there _any_ keys from cr.yaml. We even don't discuss different MongoDB versions there. So if we are going to mention some cluster customization options in our installation guides, it's a separate task related to a number of features to be mentioned.

2021-02-26 12:59 UTC, spron-in requested changes

2021-02-26 12:59 UTC, spron-in commented on source/update.rst
> +.. note:: Being enabled, Smart Updates will force the Operator to take MongoDB
```suggestion
.. note:: Being enabled, Smart Update will force the Operator to take MongoDB
```

2021-03-02 10:44 UTC, spron-in requested changes

2021-03-02 10:44 UTC, spron-in commented on source/update.rst
> +     cluster from scratch),
```suggestion
   * ``4.4-recommended``, ``4.2-recommended``, ``4.0-recommended``,
     ``3.6-recommended`` - same as above, but preserves specific major MongoDB version for newly provisioned clusters (ex. 4.2 will not be upgraded to 4.4 automatically),
```

2021-03-02 10:44 UTC, spron-in commented on source/update.rst
> +     creating a MongoDB 4.2, 4.0, or 3.6 cluster from scratch),
```suggestion
   * ``4.4-latest``, ``4.2-latest``, ``4.0-latest``, ``3.6-latest`` - same as above, but preserves specific major MongoDB version for newly provisioned clusters (ex. 4.2 will not be upgraded to 4.4 automatically),
```

2021-03-02 10:44 UTC, spron-in commented on source/update.rst
>     * ``Recommended`` - automatic upgrades will choose the most recent version
```suggestion
   * ``Recommended`` - automatic upgrade will choose the most recent version
```

2021-03-02 10:44 UTC, spron-in commented on source/update.rst
>     * ``Latest`` - automatic upgrades will choose the most recent version of
```suggestion
   * ``Latest`` - automatic upgrade will choose the most recent version of
```

2021-03-02 10:44 UTC, spron-in commented on source/update.rst
>       version doesn't match the explicit version number with no future upgrades
I don't understand what we are saying here. 
specific version number should run me specific mongoDB version, right?

2021-03-02 18:46 UTC, spron-in approved these changes

2021-03-02 18:47 UTC, spron-in commented on source/update.rst
>       {{{mongodb42recommended}}}, etc.),
I'm just curious, if there is a good place where the user can find the versions he can set.

2021-03-02 18:47 UTC, spron-in approved these changes

2021-03-02 18:50 UTC, cap1984 approved these changes

2021-03-03 08:47 UTC, merged