Add logic for syncing restore with mongos
percona/percona-server-mongodb-operator pull request #575
Opened 2021-02-23 12:08 UTC by blez

2021-02-23 12:49 UTC, delgod requested changes

2021-02-23 12:49 UTC, delgod commented on pkg/controller/perconaservermongodb/backup.go
> +			rst.Status.State != api.RestoreStateError {
```suggestion
			rst.Status.State != api.RestoreStateError && 
			rst.Spec.ClusterName == cr.Name {
```

2021-02-23 12:49 UTC, delgod commented on pkg/controller/perconaservermongodb/backup.go
> +			bcp.Status.State != api.BackupStateError {
```suggestion
			bcp.Status.State != api.BackupStateError &&
			bcp.Spec.PSMDBCluster == cr.Name {
```

2021-02-23 14:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| security-context | passed |
| arbiter | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/575/commits/0a15f89d073ed7532576c7b6b267ec9bc9b38522
image: `perconalab/percona-server-mongodb-operator:PR-575-0a15f89d`

2021-02-23 14:29 UTC, delgod requested changes

2021-02-23 14:29 UTC, delgod commented on pkg/controller/perconaservermongodb/balancer.go
> +	)
```suggestion
	mongosPods, err := r.getMongosPods(cr)
```

2021-02-23 14:29 UTC, delgod commented on pkg/controller/perconaservermongodb/psmdb_controller.go
> +
I think we should delete stop balancer and delete mongos from `runRestore` function.
Why we run `doInCaseOfRestore` here?

2021-02-23 14:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing | passed |
| limits | passed |
| arbiter | passed |
| scaling | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| security-context | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/575/commits/de1568a97ef41bc222d4c6424d75a85c6a705a13
image: `perconalab/percona-server-mongodb-operator:PR-575-de1568a9`

2021-02-23 15:20 UTC, delgod approved these changes

2021-02-23 16:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/575/commits/b5aba832b19f820b547a5722cebdf027e73b13eb
image: `perconalab/percona-server-mongodb-operator:PR-575-b5aba832`

2021-02-23 17:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/575/commits/be788e8e0c05b9a913a4584d3c0cd1b3664d6994
image: `perconalab/percona-server-mongodb-operator:PR-575-be788e8e`

2021-02-24 07:21 UTC, qJkee approved these changes

2021-02-24 07:42 UTC, merged