K8SPSMDB-396 document how to use Red Hat Marketplace
percona/percona-server-mongodb-operator pull request #585
Opened 2021-02-25 12:49 UTC by fiowro

2021-02-26 10:03 UTC, cap1984 submitted a review, later dismissed

2021-03-02 09:17 UTC, spron-in requested changes

2021-03-02 09:17 UTC, spron-in commented on source/openshift.rst
> +* Using the Operator to make actual Percona Server for MongoDB installation.
```suggestion
* Install Percona Server for MongoDB using the Operator.
```

2021-03-02 09:17 UTC, spron-in commented on source/openshift.rst
> +3. When finished, chose ``Worspace->Sofware`` in the system menu on the top and chouse the Operator:
```suggestion
3. When finished, chose ``Workspace->Software`` in the system menu on the top and choose the Operator:
```

2021-03-02 09:18 UTC, spron-in approved these changes

2021-03-02 09:49 UTC, cap1984 approved these changes

2021-03-02 10:05 UTC, merged