K8SPSMDB-331 feature: Restrict running min pods of mongos
percona/percona-server-mongodb-operator pull request #619
Opened 2021-03-16 16:38 UTC by pooknull

https://jira.percona.com/browse/K8SPSMDB-331

Restricted running less than 2 pods of mongos unless allowUnsafeConfigurations flag is set to true by changing mongos size to 2 if it's lower than that.

2021-03-16 16:38 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=619) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-server-mongodb-operator?pullRequest=619) it.</sub>

2021-03-16 18:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/619/commits/7ecf17675b4443236e4daf83923cc8baade4a726
image: `perconalab/percona-server-mongodb-operator:PR-619-7ecf1767`

2021-03-17 08:05 UTC, delgod requested changes

2021-03-17 08:05 UTC, delgod commented on pkg/apis/psmdb/v1/psmdb_defaults.go
> +			if !cr.Spec.UnsafeConf && cr.Spec.Sharding.Mongos.Size < minSafeMongosSize {
what if `cr.Spec.Sharding.Mongos == nil`

2021-03-17 10:03 UTC, qJkee approved these changes

2021-03-17 10:34 UTC, delgod approved these changes

2021-03-17 13:29 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| one-pod | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/619/commits/62c467a8f0480f793c397b9e68c13e27b6ab48ed
image: `perconalab/percona-server-mongodb-operator:PR-619-62c467a8`

2021-03-17 13:48 UTC, merged