K8SPSMDB-430: checking UID before deleting sts
percona/percona-server-mongodb-operator pull request #629
Opened 2021-04-06 19:50 UTC by srteam2020

Fixing https://jira.percona.com/browse/K8SPSMDB-430
Double checking the UID of the controllerRef of the statefulset before deleting it in `deleteAllStatefulsets`.
It seems that PVC is not tagged with the controllerRef. We can later issue another patch to label PVC with UID of PerconaServerMongoDB and perform the check before deleting PVC.

2021-04-06 19:50 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-server-mongodb-operator?pullRequest=629) it.</sub>

2021-04-06 22:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| self-healing | passed |
| arbiter | passed |
| scheduled-backup | passed |
| scaling | passed |
| security-context | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/629/commits/f303eb0ca6b38aff64a8e7147c4c9feb15b06089
image: `perconalab/percona-server-mongodb-operator:PR-629-f303eb0c`

2021-04-07 05:02 UTC, delgod approved these changes

2021-04-08 11:22 UTC, qJkee requested changes
I think it's better to do this check at `r.getAllStatefulsets` to be sure that we will not have such issues in future.
We can simply filter them by iterating and checking with `metav1.IsControlledBy` function and return only cr related items

2021-04-09 17:54 UTC, srteam2020 commented
> I think it's better to do this check at `r.getAllStatefulsets` to be sure that we will not have such issues in future.
> We can simply filter them by iterating and checking with `metav1.IsControlledBy` function and return only cr related items
> @delgod what do you think?

yes we can move the check to `getAllStatefulsets`. Will try to push today or tmr.

2021-04-10 18:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scheduled-backup | passed |
| arbiter | passed |
| scaling | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| security-context | passed |
| liveness | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/629/commits/834a9b6d02edb020b5ad387f0db140a041f309f5
image: `perconalab/percona-server-mongodb-operator:PR-629-834a9b6d`

2021-04-12 04:58 UTC, qJkee commented on pkg/controller/perconaservermongodb/getters.go
> +		if string(cr.GetUID()) == string(ref.UID) {
You don't need to compare UID's manually
All can be done via `metav1.IsControlledBy(obj,cr)`

2021-04-12 07:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/629/commits/bf3691b1b487514d3293f3d75d647f7247b2cb47
image: `perconalab/percona-server-mongodb-operator:PR-629-bf3691b1`

2021-04-12 09:59 UTC, qJkee approved these changes

2021-04-12 16:17 UTC, delgod approved these changes

2021-04-12 16:17 UTC, merged