K8SPSMDB-448 document major version upgrades
percona/percona-server-mongodb-operator pull request #658
Opened 2021-05-05 00:46 UTC by fiowro

2021-05-05 15:42 UTC, spron-in requested changes

2021-05-05 15:42 UTC, spron-in commented on source/operator.rst
> ++-----------------+---------------------------------------------------------------------------------------------+
I don't like the wording here. It does not turn off/on the FCV. If enabled FCV will be set to match the version during major version upgrade.

2021-05-05 15:42 UTC, spron-in commented on source/update.rst
> +to make sure backwards-incompatible features are not not automatically enabled
```suggestion
to make sure backwards-incompatible features are not automatically enabled 
```

2021-05-05 15:42 UTC, spron-in commented on source/update.rst
> +with the major version upgrade (which is recommended and safe behavior).
Would be great to expand here, that setting FCV is NOT recommended right after binaries are upgraded. It is recommended to upgrade the binaries by setting apply: flag, then waiting for few hours and check if everything is working and only after that set the setFCV flag to true. 
Setting setFCV flag to true with apply: flag at the same time should be done only if the whole procedure is tested on staging and the user is 100% sure about it. 

It is important, cause for now we do not support automated rollback if FCV is set (which we mention below).

2021-05-05 19:22 UTC, tplavcic approved these changes

2021-05-06 08:41 UTC, spron-in approved these changes

2021-05-06 08:42 UTC, merged