K8SPSMDB-389 document pitr
percona/percona-server-mongodb-operator pull request #659
Opened 2021-05-05 14:07 UTC by fiowro

2021-05-05 15:53 UTC, spron-in requested changes

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +The Operator supports the ability to perform a full restore on a PostgreSQL
```suggestion
The Operator supports the ability to perform a full restore on a MongoDB
```

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +Following steps are needed to to roll back the cluster to a
```suggestion
Following steps are needed to roll back the cluster to a
```

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +
```suggestion
```

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +
I don't understand why we need Details here :)

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +   clusters can be listed with the following command:
This is not right. In the spec we say that backupName is needed. We do that to ensure that user knows which backup to use and where oplogs are. It is to cover the case where user adds new S3 bucket if PITR is enabled and some other weird  cases.

2021-05-05 15:53 UTC, spron-in commented on source/backups.rst
> +
I would love to mention here, that the user needs to take full backup for PITR to function. PBM will not opload if there is no full backup.
This is true for new clusters and also true for clusters which just recovered from backup.

2021-05-05 17:02 UTC, dAdAbird approved these changes

2021-05-05 19:18 UTC, tplavcic approved these changes

2021-05-06 08:39 UTC, spron-in approved these changes

2021-05-06 08:40 UTC, merged