K8SPSMDB-329: improve object updates
percona/percona-server-mongodb-operator pull request #670
Opened 2021-05-20 15:24 UTC by qJkee

2021-05-20 17:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| init-deploy | passed |
| one-pod | failed |
| upgrade-consistency | failed |
| demand-backup | failed |
| self-healing | passed |
| limits | failed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | failed |
| security-context | failed |
| operator-self-healing | passed |
| demand-backup-sharded | failed |
| arbiter | failed |
| rs-shard-migration | failed |
| service-per-pod | failed |
| upgrade | passed |
| liveness | failed |
| upgrade-sharded | failed |
| smart-update | failed |
| version-service | failed |
| pitr | failed |
| pitr-sharded | failed |
| users | passed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/ba379cd29de29a58cb339efb18f3f004d3d6b13f
image: `perconalab/percona-server-mongodb-operator:PR-670-ba379cd2`

2021-05-21 12:28 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| rs-shard-migration | failed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | failed |
| users | passed |
| data-sharded | failed |
| pitr | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/4e93e505def25e0c7e1bc303ba975bde52c26ee6
image: `perconalab/percona-server-mongodb-operator:PR-670-4e93e505`

2021-05-27 11:02 UTC, delgod submitted a review, later dismissed

2021-06-01 12:16 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup-sharded | failed |
| rs-shard-migration | failed |
| arbiter | passed |
| service-per-pod | failed |
| upgrade | passed |
| upgrade-sharded | failed |
| pitr | passed |
| pitr-sharded | failed |
| liveness | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/5552642a8e6f668a9722a9b38b214ebdc0edbcf3
image: `perconalab/percona-server-mongodb-operator:PR-670-5552642a`

2021-06-01 18:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| init-deploy | passed |
| limits | passed |
| data-sharded | failed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | failed |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | failed |
| pitr | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/4e93e505def25e0c7e1bc303ba975bde52c26ee6
image: `perconalab/percona-server-mongodb-operator:PR-670-4e93e505`

2021-06-08 13:19 UTC, delgod submitted a review, later dismissed

2021-06-09 17:25 UTC, hors requested changes
@qJkee  'some-name-mongos' service  is constantly  recreated
```
some-name-mongos   ClusterIP   10.7.242.40   <none>        27017/TCP   4s
some-name-mongos   ClusterIP   10.7.242.40   <none>        27017/TCP   8s
some-name-mongos   ClusterIP   10.7.243.137   <none>        27017/TCP   0s
some-name-mongos   ClusterIP   10.7.243.137   <none>        27017/TCP   9s
some-name-mongos   ClusterIP   10.7.242.116   <none>        27017/TCP   0s
some-name-mongos   ClusterIP   10.7.242.116   <none>        27017/TCP   9s
some-name-mongos   ClusterIP   10.7.252.244   <none>        27017/TCP   0s
some-name-mongos   ClusterIP   10.7.252.244   <none>        27017/TCP   8s
some-name-mongos   ClusterIP   10.7.246.253   <none>        27017/TCP   0s
```

2021-06-11 10:20 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | failed |
| version-service | passed |
| pitr | passed |
| users | passed |
| pitr-sharded | failed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/f91234516d59f0df6ed96d7e12d09ee18b5fdcff
image: `perconalab/percona-server-mongodb-operator:PR-670-f9123451`

2021-06-11 12:26 UTC, egegunes commented on pkg/controller/perconaservermongodb/psmdb_controller.go
> +	if cr.CompareVersion("1.8.0") >= 0 {
`1.8.0` or `1.9.0` ?

2021-06-11 17:02 UTC, delgod commented on pkg/controller/perconaservermongodb/psmdb_controller.go
> +	if cr.CompareVersion("1.8.0") >= 0 {
`1.9.0`

2021-06-13 19:49 UTC, qJkee commented on pkg/controller/perconaservermongodb/psmdb_controller.go
> +	if cr.CompareVersion("1.8.0") >= 0 {
fixed in 757afff

2021-06-13 22:38 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| upgrade | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | failed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/757afffd79b54c5327acf71994306b70302d567b
image: `perconalab/percona-server-mongodb-operator:PR-670-757afffd`

2021-06-14 05:46 UTC, delgod approved these changes

2021-06-14 06:14 UTC, egegunes approved these changes

2021-06-14 06:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| storage | passed |
| version-service | passed |
| self-healing | passed |
| users | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/670/commits/757afffd79b54c5327acf71994306b70302d567b
image: `perconalab/percona-server-mongodb-operator:PR-670-757afffd`

2021-06-14 06:27 UTC, merged