K8SPSMDB-459 mention cluster name limitations
percona/percona-server-mongodb-operator pull request #672
Opened 2021-05-27 23:41 UTC by fiowro

2021-05-28 04:24 UTC, delgod submitted a review, later dismissed

2021-06-01 08:17 UTC, spron-in requested changes
This is not right.
Try settin

2021-06-01 08:17 UTC, spron-in commented on source/operator.rst
> +  for MongoDB Cluster; it should include only `URL-compatible characters <https://datatracker.ietf.org/doc/html/rfc3986#section-2.3>`_ and should not exceed 22 characters;
This is not fully correct. Try setting the name like 123cluster, Operator will throw you the error:
```
{"level":"error","ts":1622535167.1972747,"logger":"controller","msg":"Reconciler error","controller":"perconaxtradbcluster-controller","name":"123cluster","namespace":"default","error":"create PXC ServiceUnready: create: Service \"123cluster-pxc-unready\" is invalid: metadata.name: Invalid value: \"123cluster-pxc-unready\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","
```

2021-06-01 08:18 UTC, spron-in commented on source/operator.rst
> +  for MongoDB Cluster; it should include only `URL-compatible characters <https://datatracker.ietf.org/doc/html/rfc3986#section-2.3>`_ and should not exceed 22 characters;
The PR here also has the same flaw: https://github.com/percona/percona-xtradb-cluster-operator/pull/887

2021-06-08 12:37 UTC, delgod submitted a review, later dismissed

2021-06-09 10:04 UTC, hors approved these changes

2021-06-11 07:11 UTC, delgod approved these changes

2021-06-11 11:35 UTC, spron-in approved these changes

2021-06-11 11:37 UTC, merged