K8SPSMDB-486: Fix cluster crash on losing majority due to downscale
percona/percona-server-mongodb-operator pull request #695
Opened 2021-06-15 06:38 UTC by egegunes

2021-06-15 07:12 UTC, delgod reviewed
is it works?

2021-06-15 07:27 UTC, delgod submitted a review, later dismissed

2021-06-15 09:54 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | failed |
| security-context | passed |
| self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| smart-update | failed |
| pitr | passed |
| pitr-sharded | passed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/c8a48240cf8981e68a625a9184d822a7e7965016
image: `perconalab/percona-server-mongodb-operator:PR-695-c8a48240`

2021-06-15 13:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | failed |
| security-context | passed |
| self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| operator-self-healing-chaos | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| smart-update | failed |
| pitr | passed |
| pitr-sharded | passed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/a123851d03cfa7910f6a455fcd9381d4510b1a11
image: `perconalab/percona-server-mongodb-operator:PR-695-a123851d`

2021-06-16 10:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| data-sharded | passed |
| upgrade-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/a8e4b7cef396ef61079a6ca81357336243cb5b02
image: `perconalab/percona-server-mongodb-operator:PR-695-a8e4b7ce`

2021-06-16 10:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/477667f58ff3bc2a53f55e1621dd053f3ee260ab
image: `perconalab/percona-server-mongodb-operator:PR-695-477667f5`

2021-06-16 10:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| upgrade | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| version-service | passed |
| pitr | passed |
| users | failed |
| data-sharded | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/61a786b4816280a2e0dab007f9f3bca396046ff3
image: `perconalab/percona-server-mongodb-operator:PR-695-61a786b4`

2021-06-16 12:13 UTC, delgod submitted a review, later dismissed

2021-06-17 09:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/477667f58ff3bc2a53f55e1621dd053f3ee260ab
image: `perconalab/percona-server-mongodb-operator:PR-695-477667f5`

2021-06-17 21:16 UTC, hors requested changes

2021-06-17 21:16 UTC, hors commented on docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md
> +in a manner that causes cluster failure. For example, if an user has a 7 member
```suggestion
in a manner that causes cluster failure. For example, if a user has 7 members
```

2021-06-17 21:16 UTC, hors commented on docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md
> +replicaSet and downscales it to 3 members, the cluster is going to lose
```suggestion
of replicaSet and downscales it to 3 members, the cluster is going to lose
```

2021-06-17 21:16 UTC, hors commented on docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md
> +* Rather than populating replicaSet members based on a set of pods that selected
```suggestion
* Rather than populating replicaSet members based on a set of pods that are selected
```

2021-06-17 21:16 UTC, hors commented on docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md
> +  by labels, we could fetch pods one by one in respect to replicaSet size and
```suggestion
  according to labels, we could fetch pods one by one in respect to replicaSet size and
```

2021-06-17 21:16 UTC, hors commented on docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md
> +CR is updated by operator before the replicaSet reachs the target size, we'll
```suggestion
CR is updated by operator before the replicaSet reaches the target size, we'll
```

2021-06-21 07:03 UTC, delgod approved these changes

2021-06-21 08:31 UTC, qJkee approved these changes

2021-06-21 08:46 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | failed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/beaeb19c7e31a20c190451fea3ae35f109c22e3c
image: `perconalab/percona-server-mongodb-operator:PR-695-beaeb19c`

2021-06-21 09:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/695/commits/beaeb19c7e31a20c190451fea3ae35f109c22e3c
image: `perconalab/percona-server-mongodb-operator:PR-695-beaeb19c`

2021-06-21 10:01 UTC, merged