K8SPSMDB-172 configmaps for MongoDB
percona/percona-server-mongodb-operator pull request #698
Opened 2021-06-15 07:59 UTC by fiowro

2021-06-18 06:45 UTC, spron-in submitted a review, later dismissed

2021-06-21 07:49 UTC, tplavcic requested changes

2021-06-21 07:49 UTC, tplavcic commented on source/operator.rst
> +|                 |       mode: slowOp										|
`mongos` doesn't support `operationProfiling.mode` option so I propose to remove it and just leave systemLog example.

2021-06-22 16:38 UTC, tplavcic reviewed
The thing with these secrets is that they can be stored in 3 places:
- configuration key inside cr.yaml (when used it creates configmap in the background)
- create manually configmaps
- create special secrets

The thing with secrets and configmaps is that they need to be called specifically so that operator can find them.

Here's how to create configmaps for sharding cluster:
```
kubectl create configmap my-cluster-name-rs0-mongod --from-file=mongod.conf=mongod.conf
kubectl create configmap my-cluster-name-cfg-mongod --from-file=mongod.conf=mongod.conf
kubectl create configmap my-cluster-name-mongos --from-file=mongos.conf=mongos.conf
```

Here's the example of the secrets:
```
$ cat mongod-rs0-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-name-rs0-mongod
data:
  mongod.conf: ICAgICAgb3BlcmF0aW9uUHJvZmlsaW5nOgogICAgICAgIG1vZGU6IHNsb3dPcAogICAgICBzeXN0ZW1Mb2c6CiAgICAgICAgdmVyYm9zaXR5OiAxCg==
```

here's PXC page for configmaps - it doesn't include secrets: https://www.percona.com/doc/kubernetes-operator-for-pxc/options.html#use-a-configmap

2021-06-28 09:08 UTC, tplavcic approved these changes

2021-06-29 12:14 UTC, hors approved these changes

2021-06-29 12:50 UTC, merged