K8SPSMDB-515: Allow setting TLS mode for mongod
percona/percona-server-mongodb-operator pull request #730
Opened 2021-07-14 11:31 UTC by egegunes

2021-07-14 14:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/ab1d88b0743cb58955c959ff966449c4f31e80eb
image: `perconalab/percona-server-mongodb-operator:PR-730-ab1d88b0`

2021-07-15 09:07 UTC, spron-in requested changes

2021-07-15 09:07 UTC, spron-in commented on deploy/cr.yaml
> +#       mode: preferSSL
We want to deprecate the whole spec.mongod section.
Also preferSSL is not only for mongod.
What about changing this flag in the custom configuration?

2021-07-19 08:35 UTC, qJkee commented on pkg/apis/psmdb/v1/psmdb_defaults.go
> +		cr.Spec.Mongod.Net.TLS = &MongodSpecNetTLS{}
we can auto fill mode there. Next if don't needed

2021-07-29 13:51 UTC, nonemax requested changes

2021-07-29 13:51 UTC, nonemax commented on deploy/cr.yaml
> +  image: perconalab/percona-server-mongodb-operator:k8spsmdb-515-mongod4.4
And this to

2021-07-29 13:51 UTC, nonemax commented on deploy/cr.yaml
> +  initImage: perconalab/percona-server-mongodb-operator:k8spsmdb-515
I think you forgot to remove this image

2021-07-29 16:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | failed |
| upgrade-consistency | failed |
| one-pod | failed |
| demand-backup | failed |
| self-healing | passed |
| limits | failed |
| scaling | passed |
| scheduled-backup | failed |
| security-context | failed |
| self-healing-chaos | passed |
| demand-backup-sharded | failed |
| rs-shard-migration | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| monitoring-2-0 | failed |
| arbiter | failed |
| service-per-pod | failed |
| upgrade | failed |
| liveness | failed |
| upgrade-sharded | failed |
| smart-update | failed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/e786030a59bece08b5b1dd1b0e4eb45cbb128ac8
image: `perconalab/percona-server-mongodb-operator:PR-730-e786030a`

2021-08-02 11:17 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| pitr | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| pitr-sharded | failed |
| smart-update | passed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/839478d1f04563a06d5acd4e6f04f405e8eebb35
image: `perconalab/percona-server-mongodb-operator:PR-730-839478d1`

2021-08-02 13:23 UTC, delgod requested changes

2021-08-03 06:57 UTC, egegunes commented on build/ps-entry.sh
> +                    _mongod_hack_ensure_arg_val --tlsMode "$tlsMode" "${mongodHackedArgs[@]}"
no, we didn't change it. if user doesn't pass the tls mode with custom config, we use `preferTLS` as default: https://github.com/percona/percona-server-mongodb-operator/blob/K8SPSMDB-515/build/ps-entry.sh#L425-L430

2021-08-05 07:05 UTC, delgod commented on build/ps-entry.sh
> +                    _mongod_hack_ensure_arg_val --tlsMode "$tlsMode" "${mongodHackedArgs[@]}"
lets have a call

2021-08-05 11:58 UTC, qJkee submitted a review, later dismissed

2021-08-23 14:57 UTC, qJkee approved these changes

2021-08-23 16:28 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| one-pod | failed |
| self-healing | passed |
| demand-backup | failed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| scheduled-backup | failed |
| operator-self-healing-chaos | passed |
| demand-backup-sharded | failed |
| upgrade | failed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/0c3b42b21a101bb58beac25b6610edd0d858dfa9
image: `perconalab/percona-server-mongodb-operator:PR-730-0c3b42b2`

2021-08-24 09:33 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| self-healing | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| scheduled-backup | failed |
| operator-self-healing-chaos | passed |
| demand-backup-sharded | failed |
| monitoring-2-0 | passed |
| upgrade | failed |
| rs-shard-migration | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/3cd2626366e29556e8b7245f08169ac3a6fef52d
image: `perconalab/percona-server-mongodb-operator:PR-730-3cd26263`

2021-08-24 10:33 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | failed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | failed |
| operator-self-healing | passed |
| liveness | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| version-service | failed |
| demand-backup-sharded | failed |
| users | failed |
| data-sharded | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/338dba79230b7dadbe93c01890f9d55daf3243e2
image: `perconalab/percona-server-mongodb-operator:PR-730-338dba79`

2021-08-31 09:49 UTC, delgod requested changes

2021-08-31 09:49 UTC, delgod commented on pkg/controller/perconaservermongodb/mgo.go
> +			}
but these transformations are done inside the entrypoint. see - https://github.com/percona/percona-server-mongodb-operator/blob/main/build/ps-entry.sh#L420

I am not sure if we should duplicate logic here?
```suggestion
			mongoCmd += " --ssl --sslPEMKeyFile /tmp/tls.pem --sslAllowInvalidCertificates --sslCAFile /etc/mongodb-ssl/ca.crt"
```

2021-08-31 10:50 UTC, delgod submitted a review, later dismissed

2021-09-16 01:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| limits | passed |
| data-sharded | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | failed |
| scheduled-backup | failed |
| demand-backup-sharded | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/c205289b7ebfcb8befe1a8228e405d43c4ed1be0
image: `perconalab/percona-server-mongodb-operator:PR-730-c205289b`

2021-11-19 12:10 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | failed |
| init-deploy | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| limits | passed |
| arbiter | passed |
| demand-backup | failed |
| scaling | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| scheduled-backup | failed |
| users | failed |
| demand-backup-sharded | failed |
| data-sharded | passed |
| non-voting | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/a6b37284f3c64b645d592b66c5934a919cb99b1f
image: `perconalab/percona-server-mongodb-operator:PR-730-a6b37284`

2021-11-19 12:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | failed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| demand-backup | failed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| scheduled-backup | failed |
| users | failed |
| data-sharded | passed |
| demand-backup-sharded | failed |
| non-voting | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/730/commits/77f0f97894b8702e3835da26477a2fe955b871bd
image: `perconalab/percona-server-mongodb-operator:PR-730-77f0f978`

2022-03-08 13:27 UTC, egegunes commented
Closing this until I'm available to give another shot.

2022-03-08 13:27 UTC, closed without merging