K8SPSMDB-501 add non-voting member options
percona/percona-server-mongodb-operator pull request #747
Opened 2021-08-31 08:23 UTC by fiowro

2021-09-07 05:12 UTC, egegunes approved these changes

2021-09-09 19:10 UTC, spron-in requested changes

2021-09-09 19:10 UTC, spron-in commented on source/arbiter.rst
> +election process. This feature is required if having more than 7 nodes, or if
```suggestion
election process. This feature is required to have more than 7 nodes, or if
```

2021-09-09 19:10 UTC, spron-in commented on source/arbiter.rst
> +
Lets also add a link to replication with smth like "it is possible to add a non-voting node in the edge location through externalNodes option. Please refer to replication doc". You mention edge below, maybe there a good place as well

2021-09-15 09:24 UTC, spron-in approved these changes

2021-09-17 13:01 UTC, merged