K8SPSMDB-265 cross region replication docs
percona/percona-server-mongodb-operator pull request #761
Opened 2021-09-08 10:01 UTC by fiowro

2021-09-09 04:41 UTC, egegunes requested changes

2021-09-09 19:04 UTC, spron-in requested changes

2021-09-09 19:04 UTC, spron-in commented on source/replication.rst
> +can configure this information in the ``replsets.externalNodes`` and
know and information are killing the vibe

2021-09-09 19:04 UTC, spron-in commented on source/replication.rst
> +can configure this information in the ``replsets.externalNodes`` and
user does not need to add external nodes on replica at all. not for config servers, not for replsets.

2021-09-09 19:04 UTC, spron-in commented on source/replication.rst
> +       - host: rs0-repl1.percona.com
this is not needed on replica.

2021-09-09 19:04 UTC, spron-in commented on source/replication.rst
> +         - host: rs0-repl1.percona.com
not needed on replica

2021-09-09 19:04 UTC, spron-in commented on source/replication.rst
> +``my-cluster-name-ssl``, and ``my-cluster-name-ssl-internal`` by default).
ah, I see it now. Lets move it to corresponding section?

2021-09-22 22:18 UTC, fiowro commented on source/replication.rst
> +executing ``kubectl get services -l "app.kubernetes.io/instance=CLUSTER_NAME"`` command.
yes)

2021-09-23 10:55 UTC, merged