K8SPSMDB-527 timeout should be less or equal than period
percona/percona-server-mongodb-operator pull request #812
Opened 2021-11-22 07:49 UTC by delgod

[K8SPSMDB-527](https://jira.percona.com/browse/K8SPSMDB-527)

timeout should be less or equal than the period otherwise possible to get errors in some configurations
```
  Normal   LoadBalancerNegWithoutHealthCheck  10m   neg-readiness-reflector  Pod is in NEG "Key{\"k8s1-2615dab0-run-main-4664-my-cluster-name-mongo-2701-24107fd7\", zone: \"europe-west1-c\"}". NEG is not attached to any BackendService with health checking. Marking condition "cloud.google.com/load-balancer-neg-ready" to True.
  ```

2021-11-22 08:06 UTC, hors submitted a review, later dismissed

2021-11-22 09:11 UTC, defbin approved these changes

2021-11-22 10:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | failed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/52bc2864ac0c26d4605ece2d32e851f4fa87362a
image: `perconalab/percona-server-mongodb-operator:PR-812-52bc2864`

2021-11-22 11:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | failed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| init-deploy | passed |
| operator-self-healing-chaos | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/52bc2864ac0c26d4605ece2d32e851f4fa87362a
image: `perconalab/percona-server-mongodb-operator:PR-812-52bc2864`

2021-11-22 12:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | failed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/52bc2864ac0c26d4605ece2d32e851f4fa87362a
image: `perconalab/percona-server-mongodb-operator:PR-812-52bc2864`

2021-11-22 15:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | failed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/3b5345d2803a8a7d077640ee6de2fcf031a44866
image: `perconalab/percona-server-mongodb-operator:PR-812-3b5345d2`

2021-11-22 16:14 UTC, defbin submitted a review, later dismissed

2021-11-22 19:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | failed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/3f005260c816d7b5073bf99ec01ffb8723e17c6d
image: `perconalab/percona-server-mongodb-operator:PR-812-3f005260`

2021-11-24 08:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| self-healing-chaos | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| smart-update | passed |
| init-deploy | passed |
| version-service | passed |
| limits | passed |
| users | passed |
| scaling | passed |
| data-sharded | passed |
| non-voting | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | failed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/3f005260c816d7b5073bf99ec01ffb8723e17c6d
image: `perconalab/percona-server-mongodb-operator:PR-812-3f005260`

2021-11-24 12:49 UTC, defbin submitted a review, later dismissed

2021-11-24 14:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | failed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/bb40419cdb7991fd6bce67e7d82562a850980ad8
image: `perconalab/percona-server-mongodb-operator:PR-812-bb40419c`

2021-11-24 15:04 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/f0464b0b4f25c647942ed3b78a270d19e206f0f5
image: `perconalab/percona-server-mongodb-operator:PR-812-f0464b0b`

2021-11-24 21:27 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| storage | passed |
| version-service | passed |
| self-healing | passed |
| users | passed |
| self-healing-chaos | passed |
| data-sharded | passed |
| non-voting | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/f0464b0b4f25c647942ed3b78a270d19e206f0f5
image: `perconalab/percona-server-mongodb-operator:PR-812-f0464b0b`

2021-11-25 08:22 UTC, hors requested changes
one more test demand-backup-sharded should be fixed

2021-11-25 14:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | failed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| limits | passed |
| demand-backup | failed |
| scheduled-backup | failed |
| arbiter | passed |
| demand-backup-sharded | failed |
| scaling | passed |
| upgrade | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| security-context | failed |
| service-per-pod | passed |
| upgrade-sharded | passed |
| liveness | passed |
| rs-shard-migration | passed |
| pitr | failed |
| pitr-sharded | failed |
| smart-update | passed |
| version-service | passed |
| users | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/08cda1e16b524c0410a4beb8cb83aa41cf05bffb
image: `perconalab/percona-server-mongodb-operator:PR-812-08cda1e1`

2021-11-26 14:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-chaos | passed |
| scaling | passed |
| security-context | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| demand-backup-sharded | failed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/08cda1e16b524c0410a4beb8cb83aa41cf05bffb
image: `perconalab/percona-server-mongodb-operator:PR-812-08cda1e1`

2021-11-26 21:20 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| storage | passed |
| users | passed |
| self-healing | passed |
| data-sharded | passed |
| self-healing-chaos | passed |
| non-voting | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/08cda1e16b524c0410a4beb8cb83aa41cf05bffb
image: `perconalab/percona-server-mongodb-operator:PR-812-08cda1e1`

2021-11-26 23:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | failed |
| demand-backup | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| scheduled-backup | failed |
| liveness | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | failed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/31b7392c2263c2380bb6318f15d76122ceab1dcc
image: `perconalab/percona-server-mongodb-operator:PR-812-31b7392c`

2021-11-27 07:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-chaos | passed |
| scaling | passed |
| operator-self-healing | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/812/commits/31b7392c2263c2380bb6318f15d76122ceab1dcc
image: `perconalab/percona-server-mongodb-operator:PR-812-31b7392c`

2021-11-27 07:25 UTC, defbin approved these changes

2021-11-27 09:41 UTC, hors approved these changes

2021-11-27 09:41 UTC, merged