[K8SPSMDB-609] Store additional S3 settings into PBM config
percona/percona-server-mongodb-operator pull request #831
Opened 2021-12-08 22:19 UTC by dalbani

https://jira.percona.com/browse/K8SPSMDB-609

2021-12-08 22:32 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/831/commits/018756e4186e9739a182bdc98601efd2398a8fcd
image: `perconalab/percona-server-mongodb-operator:PR-831-018756e4`

2021-12-09 09:33 UTC, hors requested changes

2021-12-09 09:48 UTC, defbin commented
LGTM

2021-12-09 09:58 UTC, dalbani commented on pkg/apis/psmdb/v1/psmdb_types.go
> +	StorageClass      string `json:"storageClass,omitempty"`
I have just included an example in `deploy/cr.yaml`, based on the default values.
Is that what you had in mind?

2021-12-09 10:01 UTC, dalbani commented
Rebased on `main`.

2021-12-09 10:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/831/commits/484c390b4e38a2837ab229a4af02aa055617429d
image: `perconalab/percona-server-mongodb-operator:PR-831-484c390b`

2021-12-09 10:06 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/831/commits/479e2f7be239b30cca749a2597e7a7fb4617b393
image: `perconalab/percona-server-mongodb-operator:PR-831-479e2f7b`

2021-12-09 10:33 UTC, delgod approved these changes

2021-12-09 13:01 UTC, hors approved these changes

2021-12-09 13:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | failed |
| smart-update | passed |
| version-service | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/831/commits/8580a99df5815b67aa73fa265ac1facabb8b5a00
image: `perconalab/percona-server-mongodb-operator:PR-831-8580a99d`

2021-12-09 15:44 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| init-deploy | passed |
| users | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/831/commits/8580a99df5815b67aa73fa265ac1facabb8b5a00
image: `perconalab/percona-server-mongodb-operator:PR-831-8580a99d`

2021-12-09 15:45 UTC, defbin approved these changes

2021-12-09 15:55 UTC, merged

2021-12-09 16:00 UTC, dalbani commented
Cool 😎