CLOUD-691 rename the operator in docs
percona/percona-server-mongodb-operator pull request #931
Opened 2022-04-08 16:37 UTC by fiowro

2022-04-15 14:03 UTC, spron-in requested changes

2022-04-15 14:03 UTC, spron-in commented on source/index.rst
> +The `Percona Kubernetes Operatorfor MongoDB <https://github.com/percona/percona-server-mongodb-operator>`_ automates the creation, modification, or deletion of items in your Percona Server for MongoD
```suggestion
The `Percona Operator for MongoDB <https://github.com/percona/percona-server-mongodb-operator>`_ automates the creation, modification, or deletion of items in your Percona Server for MongoDB environment. The Operator contains the necessary Kubernetes settings to maintain a consistent Percona Server for MongoDB instance. modification, or deletion of items in your Percona Server for MongoDB environment. The Operator contains the necessary Kubernetes settings to maintain a consistent Percona Server for MongoDB instance.
```

2022-04-19 08:44 UTC, spron-in approved these changes

2022-04-25 08:58 UTC, tplavcic approved these changes

2022-04-25 08:59 UTC, merged